####################################### Services
services:
  node-exporter:
    image: prom/node-exporter
    container_name: monitor-node-exporter-c
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
    pid: host
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    networks:
      - network-monitor
    restart: always
    # ports:
    #   - 9100:9100

####################################### Networks
networks:
  network-monitor:
    external: true
