####################################### Services
services:
  service-node-exporter:
    image: ahmettoguz/node-exporter:v1.9.1
    container_name: container-node-exporter
    command:
      - "--path.rootfs=/rootfs"
    volumes:
      - /:/rootfs:ro
    networks:
      - network-monitor
    restart: ${RESTART_POLICY}
    # ports:
    #   - 9100:9100

####################################### Networks
networks:
  network-monitor:
    external: true
