####################################### Services
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: monitor-node-exporter-c
    command:
      - "--path.rootfs=/host"
    pid: host
    volumes:
      - "/:/host,rslave"
    networks:
      - network-monitor
    restart: always
    # ports:
    #   - 9100:9100

####################################### Networks
networks:
  network-monitor:
    external: true
